<a href="https://colab.research.google.com/github/yusufmkh/recommender-model/blob/main/RecommenderModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import pandas as pd

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
candidate_samples = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/candidate_samples.xlsx')
job_samples = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/job_samples.xlsx')

In [12]:
candidate_samples

,skill_1,skill_2,skill_3,skill_4,skill_5,restaurant,hotel,smallCompany,mediumCompany,largeCompany,fulltimeJob,parttimeJob,contractJob,pay20_30,pay30_35,pay35_40,pay40_45,pay45_50,pay50plus
0,3,4,2,5,1,1,0,1,1,0,1,0,1,0,1,0,0,0,0
1,2,5,4,1,3,0,1,0,1,0,0,1,1,1,0,0,0,0,0
2,5,1,3,2,4,1,1,1,1,0,1,1,1,0,0,1,0,0,0
3,4,2,3,5,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0
4,1,3,4,2,5,1,0,1,0,0,0,1,0,1,0,0,0,0,0

In [13]:
job_samples

,skill_1,skill_2,skill_3,skill_4,skill_5,restaurant,hotel,smallCompany,mediumCompany,largeCompany,fulltimeJob,parttimeJob,contractJob,pay20_30,pay30_35,pay35_40,pay40_45,pay45_50,pay50plus
0,3,4,2,5,1,1,0,1,1,0,1,0,1,0,1,0,0,0,0
1,2,5,4,1,3,0,1,0,1,0,0,1,1,1,0,0,0,0,0
2,5,1,3,2,4,0,1,1,1,0,1,1,1,0,0,1,0,0,0
3,4,2,3,5,1,1,0,0,0,1,0,1,0,1,0,0,0,0,0
4,1,3,4,2,5,1,0,1,0,0,0,1,0,1,0,0,0,0,0
5,3,4,2,5,1,1,0,1,1,0,1,0,1,0,1,0,0,0,0
6,2,5,4,1,3,0,1,0,1,0,0,1,1,1,0,0,0,0,0
7,5,1,3,2,4,0,1,1,1,0,1,1,1,0,0,1,0,0,0
8,4,2,3,5,1,1,0,0,0,1,0,1,0,1,0,0,0,0,0
9,1,3,4,2,5,1,0,1,0,0,0,1,0,1,0,0,0,0,0
10,3,4,2,5,1,1,0,1,1,0,1,0,1,0,1,0,0,0,0
11,2,5,4,1,3,0,1,0,1,0,0,1,1,1,0,0,0,0,0
12,5,1,3,2,4,0,1,1,1,0,1,1,1,0,0,1,0,0,0
13,4,2,3,5,1,1,0,0,0,1,0,1,0,1,0,0,0,0,0
14,1,3,4,2,5,1,0,1,0,0,0,1,0,1,0,0,0,0,0
15,3,4,2,5,1,1,0,1,1,0,1,0,1,0,1,0,0,0,0
16,2,5,4,1,3,0,1,0,1,0,0,1,1,1,0,0,0,0,0
17,5,1,3,2,4,0,1,1,1,0,1,1,1,0,0,1,0,0,0
18,4,2,3,5,1,1,0,0,0,1,0,1,0,1,0,0,0,0,0
19,1,3,4,2,5,1,0,1,0,0,0,1,0,1,0,0,0,0,0

In [14]:
job_samples_transposed = job_samples.transpose()
job_samples_transposed

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
skill_1,3,2,5,4,1,3,2,5,4,1,3,2,5,4,1,3,2,5,4,1
skill_2,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3
skill_3,2,4,3,3,4,2,4,3,3,4,2,4,3,3,4,2,4,3,3,4
skill_4,5,1,2,5,2,5,1,2,5,2,5,1,2,5,2,5,1,2,5,2
skill_5,1,3,4,1,5,1,3,4,1,5,1,3,4,1,5,1,3,4,1,5
restaurant,1,0,0,1,1,1,0,0,1,1,1,0,0,1,1,1,0,0,1,1
hotel,0,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1,1,0,0
smallCompany,1,0,1,0,1,1,0,1,0,1,1,0,1,0,1,1,0,1,0,1
mediumCompany,1,1,1,0,0,1,1,1,0,0,1,1,1,0,0,1,1,1,0,0
largeCompany,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
fulltimeJob,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0
parttimeJob,0,1,1,1,1,0,1,1,1,1,0,1,1,1,1,0,1,1,1,1
contractJob,1,1,1,0,0,1,1,1,0,0,1,1,1,0,0,1,1,1,0,0
pay20_30,0,1,0,1,1,0,1,0,1,1,0,1,0,1,1,0,1,0,1,1
pay30_35,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0
pay35_40,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0
pay40_45,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pay45_50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pay50plus,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [15]:
dot_predictions = np.dot(candidate_samples, job_samples_transposed)

In [16]:
dot_predictions

array([[61, 44, 43, 53, 40, 61, 44, 43, 53, 40, 61, 44, 43, 53, 40, 61,
        44, 43, 53, 40],
       [44, 60, 45, 40, 52, 44, 60, 45, 40, 52, 44, 60, 45, 40, 52, 44,
        60, 45, 40, 52],
       [44, 45, 62, 47, 47, 44, 45, 62, 47, 47, 44, 45, 62, 47, 47, 44,
        45, 62, 47, 47],
       [52, 40, 46, 58, 39, 52, 40, 46, 58, 39, 52, 40, 46, 58, 39, 52,
        40, 46, 58, 39],
       [40, 52, 46, 40, 59, 40, 52, 46, 40, 59, 40, 52, 46, 40, 59, 40,
        52, 46, 40, 59]])